In [1]:
import pandas as pd
import numpy as np

In [2]:
Immunotherapy = pd.read_csv("datamentah.csv", delimiter = ",")

In [3]:
Immunotherapy.head()

Usia   Jenis Kelamin  GDP  GDPP   TD  Nyeri  Lemas  RIWA1T  Diagnosa
0      59              1  137   215  172      0      1       1         1
1      72              1   95    90  102      1      0       1         1
2      71              0  260   221  139      0      1       1         1
3      60              0  201   102  102      1      1       1         1
4      49              0   99   116   72      1      1       1         1

In [4]:
Immunotherapy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Usia          268 non-null    int64
 1   Jenis Kelamin  268 non-null    int64
 2   GDP            268 non-null    int64
 3   GDPP           268 non-null    int64
 4   TD             268 non-null    int64
 5   Nyeri          268 non-null    int64
 6   Lemas          268 non-null    int64
 7   RIWA1T         268 non-null    int64
 8   Diagnosa       268 non-null    int64
dtypes: int64(9)
memory usage: 19.0 KB


In [5]:
# Variabel independen
x = Immunotherapy.drop(["Diagnosa"], axis = 1)
x.head()

Usia   Jenis Kelamin  GDP  GDPP   TD  Nyeri  Lemas  RIWA1T
0      59              1  137   215  172      0      1       1
1      72              1   95    90  102      1      0       1
2      71              0  260   221  139      0      1       1
3      60              0  201   102  102      1      1       1
4      49              0   99   116   72      1      1       1

In [6]:
# Variabel dependen
y = Immunotherapy["Diagnosa"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Diagnosa, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()  
scaler.fit(x_train)
x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn = KNeighborsClassifier(n_neighbors=4)

In [12]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [13]:
y_pred = knn.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0], dtype=int64)

In [14]:
knn.predict_proba(x_test)

array([[1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.  ,

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
print(confusion_matrix(y_test, y_pred))


[[24  0]
 [ 5 25]]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        24
           1       1.00      0.83      0.91        30

    accuracy                           0.91        54
   macro avg       0.91      0.92      0.91        54
weighted avg       0.92      0.91      0.91        54

